/* Baralho "Negócios". Vendas, cotação, importação e suporte de equipamento médico (Astton Medical).
   Cada chunk: [id, categoria, português, inglês, frase de exemplo].
   O id NUNCA deve mudar nem ser reaproveitado: é nele que o progresso de cada pessoa fica gravado.
   Pode acrescentar, reordenar ou corrigir texto à vontade sem perder histórico. */
window.CS_DECKS = window.CS_DECKS || {};
CS_DECKS.negocios = {
  name: 'Negócios',
  cats: [
  {key:'contato', label:'Primeiro Contato'},
  {key:'precos', label:'Cotações e Preços'},
  {key:'negociacao', label:'Negociação'},
  {key:'logistica', label:'Pedidos e Logística'},
  {key:'email', label:'E-mails e Follow-up'},
  {key:'reunioes', label:'Telefonemas e Reuniões'},
  {key:'problemas', label:'Problemas e Soluções'},
  {key:'suporte', label:'Atendimento e Suporte'},
  {key:'feiras', label:'Viagens e Feiras'}
  ],
  chunks: [
  ['f1','contato','Eu gostaria de me apresentar','I’d like to introduce myself','Hi, I’d like to introduce myself. I’m Felipe, from Astton Medical.'],
  ['f2','contato','Muito prazer em conhecê-lo','It’s a pleasure to meet you','It’s a pleasure to meet you, thanks for reaching out.'],
  ['f3','contato','Como posso ajudar?','How can I help you?','How can I help you today?'],
  ['f4','contato','Obrigado por entrar em contato','Thank you for reaching out','Thank you for reaching out about our ventilators.'],
  ['f5','contato','Vamos manter contato','Let’s stay in touch','Let’s stay in touch for future orders.'],
  ['f6','contato','Aqui está meu contato','Here’s my contact information','Here’s my contact information in case you need anything.'],
  ['f7','precos','Segue nossa melhor cotação','Please find our best quote attached','Please find our best quote attached for the 10 units.'],
  ['f8','precos','O preço inclui frete?','Does the price include shipping?','Does the price include shipping to Asunción?'],
  ['f9','precos','Podemos oferecer um desconto','We can offer a discount','We can offer a 5% discount for bulk orders.'],
  ['f10','precos','Qual é a validade dessa cotação?','How long is this quote valid?','How long is this quote valid for?'],
  ['f11','precos','O preço está sujeito a alteração','The price is subject to change','The price is subject to change without notice.'],
  ['f12','precos','Esse é o nosso melhor preço','This is our best price','This is our best price for this quantity.'],
  ['f13','negociacao','Podemos chegar a um acordo?','Can we reach an agreement?','I think we can reach an agreement on the price.'],
  ['f14','negociacao','Isso está fora do nosso orçamento','That’s outside our budget','That’s a bit outside our budget right now.'],
  ['f15','negociacao','O que você pode oferecer?','What can you offer?','What can you offer in terms of payment terms?'],
  ['f16','negociacao','Vamos encontrar um meio-termo','Let’s meet in the middle','Let’s meet in the middle on the price.'],
  ['f17','negociacao','Preciso pensar sobre isso','I need to think it over','I need to think it over and get back to you.'],
  ['f18','negociacao','Fechado!','We have a deal','Great, we have a deal then.'],
  ['f19','logistica','Quando podemos esperar o envio?','When can we expect the shipment?','When can we expect the shipment to arrive?'],
  ['f20','logistica','O pedido já foi enviado','The order has been shipped','The order has been shipped from Germany.'],
  ['f21','logistica','Precisamos confirmar o endereço de entrega','We need to confirm the delivery address','We need to confirm the delivery address before shipping.'],
  ['f22','logistica','Está fora de estoque no momento','It’s currently out of stock','It’s currently out of stock, but we expect more next week.'],
  ['f23','logistica','O prazo de entrega é de duas semanas','The delivery time is two weeks','The delivery time is about two weeks.'],
  ['f24','logistica','Vou verificar o status do pedido','I’ll check the status of the order','I’ll check the status of the order and let you know.'],
  ['f25','email','Só para dar um retorno sobre...','I just wanted to follow up on...','I just wanted to follow up on our last email.'],
  ['f26','email','Aguardo seu retorno','I look forward to hearing from you','I look forward to hearing from you soon.'],
  ['f27','email','Peço desculpas pela demora','I apologize for the delay','I apologize for the delay in my response.'],
  ['f28','email','Qualquer dúvida, estou à disposição','Please let me know if you have any questions','Please let me know if you have any questions.'],
  ['f29','email','Vou retornar até sexta','I’ll get back to you by Friday','I’ll get back to you by Friday.'],
  ['f30','email','Segue em anexo','Please find attached','Please find attached the updated invoice.'],
  ['f31','reunioes','Vamos marcar uma call?','Shall we schedule a call?','Shall we schedule a call to go over the details?'],
  ['f32','reunioes','Você pode repetir, por favor?','Could you repeat that, please?','Sorry, could you repeat that, please?'],
  ['f33','reunioes','A ligação está cortando','The call is breaking up','Sorry, the call is breaking up a little.'],
  ['f34','reunioes','Vamos direto ao ponto','Let’s get straight to the point','Let’s get straight to the point: pricing.'],
  ['f35','reunioes','Obrigado por participar da reunião','Thanks for joining the meeting','Thanks for joining the meeting today.'],
  ['f36','reunioes','Podemos remarcar?','Can we reschedule?','Can we reschedule for next week?'],
  ['f37','problemas','Sentimos muito pelo inconveniente','We’re sorry for the inconvenience','We’re sorry for the inconvenience this caused.'],
  ['f38','problemas','Vamos resolver isso o quanto antes','We’ll fix this as soon as possible','We’ll fix this as soon as possible.'],
  ['f39','problemas','A peça chegou com defeito','The part arrived damaged','The part arrived damaged during shipping.'],
  ['f40','problemas','Podemos enviar um substituto','We can send a replacement','We can send a replacement free of charge.'],
  ['f41','problemas','Obrigado pela paciência','Thank you for your patience','Thank you for your patience while we sort this out.'],
  ['f42','problemas','Vamos evitar que isso aconteça de novo','We’ll make sure this doesn’t happen again','We’ll make sure this doesn’t happen again.'],
  ['f43','suporte','Como podemos melhorar nosso atendimento?','How can we improve our service?','How can we improve our service for you?'],
  ['f44','suporte','Vamos agendar uma visita técnica','Let’s schedule a technical visit','Let’s schedule a technical visit next week.'],
  ['f45','suporte','O equipamento está na garantia','The equipment is under warranty','The equipment is still under warranty.'],
  ['f46','suporte','Precisamos de mais informações sobre o problema','We need more details about the issue','We need more details about the issue you’re facing.'],
  ['f47','suporte','Vou encaminhar para o time técnico','I’ll forward this to our technical team','I’ll forward this to our technical team right away.'],
  ['f48','suporte','Fico à disposição para o que precisar','I’m available for anything you need','I’m available for anything you need going forward.'],
  ['f49','feiras','Vamos nos encontrar na feira?','Shall we meet at the trade show?','Shall we meet at the trade show in October?'],
  ['f50','feiras','Qual estande é o seu?','Which booth is yours?','Which booth is yours at the exhibition?'],
  ['f51','feiras','Podemos marcar uma reunião presencial','We can set up an in-person meeting','We can set up an in-person meeting during the event.'],
  ['f52','feiras','Minha passagem já está confirmada','My flight is already confirmed','My flight is already confirmed for next week.'],
  ['f53','feiras','Vamos apresentar nossos novos produtos','We’re going to showcase our new products','We’re going to showcase our new products at the booth.'],
  ['f54','feiras','Foi ótimo te conhecer pessoalmente','It was great meeting you in person','It was great meeting you in person at the fair.']
  ]
};
